spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beatify?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql-root-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "ID"
            client-secret: "SECRET"
            scope: openid, profile, email

server:
  port: 8080

beatify:
  media:
    path: /Users/salar/IdeaProjects/beatify/media
