name: Build Latest Image

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package
        run: mvn Package
      - name: Prepare Artifact
        run: mkdir -p staging/target && cp -r beatify-web/target/beatify-web.war staging/target && cp Dockerfile staging/target
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: staging
  Docker:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Latest Tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: salarai/beatify:latest
          context: target/
          file: target/Dockerfile